const infoArray=[
[{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}],
[{imagesrc:"images/girl.jfif" , personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"},{imagesrc:"images/girl.jfif", personName:"HARI CHAUHAN"}]
];
const infoContainers=document.querySelectorAll(".info-container");
 
const paginationBtns=document.querySelectorAll(".pagination-btn"); 
paginationBtns.forEach((paginationBtn,index)=>{
    paginationBtn.addEventListener("click",(event)=>{ 
      
        if(event.target.classList.contains("btn"+[index]))
   
   {  
   
   infoContainers.forEach((currentInfoContainer,i)=>{ 
      
const name =document.querySelector(".info-container p");
const images=document.querySelector(".info-container img"); 
images.src=infoArray[index][i].imagesrc;
console.log(infoArray[index][i].imagesrc);
name.textContent=infoArray[index][i].personName;
           console.log(name.textContent);
           console.log(index);
       })  ;     
   }

    });

});
